import torch
import numpy as np

# Imports from config.py:
# from config import INITIAL_STATE, T_START, T_END, DT_EVAL, I_EXT_DEFAULT

def train_pinn(ground_truth_csv_path, model_save_path="pinn_model.pt", epochs=5000, lr=1e-3):
    """
    Role 8: ML Training Loop Operator
    
    Objective:
    ----------
    Executes the training loop for the Physics-Informed Neural Network (PINN).
    The loop combines two loss sources:
    1. Data Loss: The mean squared error between model predictions and the 
       ground truth trajectories at initial conditions and sampled time points.
    2. Physics Loss: The residual loss computed by the custom physics loss function (Role 7).
    After training to convergence, the module saves the model parameters (weights) 
    and returns the predicted trajectory.

    Config Variables to Import:
    --------------------------
    - INITIAL_STATE: np.ndarray of shape (4,), containing default [V_0, M_0, H_0, N_0]
    - T_START: float, start time of simulation (e.g., 0.0 ms)
    - T_END: float, end time of simulation (e.g., 100.0 ms)
    - DT_EVAL: float, output time resolution (e.g., 0.01 ms)
    - I_EXT_DEFAULT: float, default external current injection (e.g., 10.0 uA/cm^2)

    Input Parameters:
    -----------------
    - ground_truth_csv_path : str
        File path to the ground truth CSV data (generated by Role 9).
    - model_save_path : str, optional
        Destination path to save the trained PyTorch model weights. Default: "pinn_model.pt".
    - epochs : int, optional
        Number of training epochs/iterations. Default: 5000.
    - lr : float, optional
        Learning rate for the optimizer (e.g., Adam optimizer). Default: 0.001.

    Output:
    -------
    - results : np.ndarray
        NumPy array of shape (N, 5) representing the PINN's final predicted trajectory.
        The columns MUST be strictly ordered as:
        [Time, Voltage, m, h, n]
        - Column 0: Time (ms)
        - Column 1: Predicted Membrane Voltage V (mV)
        - Column 2: Predicted Sodium activation gating variable m (dimensionless)
        - Column 3: Predicted Sodium inactivation gating variable h (dimensionless)
        - Column 4: Predicted Potassium activation gating variable n (dimensionless)
        
    Side Effects:
    -------------
    - Saves the trained PyTorch model state dict to `model_save_path`.
    """
    pass
